platform :ios, '16.0'

target 'STExample' do
  
  pod 'SwiftEntryKit', :git => 'https://github.com/sharetripnet/SwiftEntryKit.git', :tag => '2.0.8'
  pod 'Kingfisher', '~> 7.6.2'
  pod 'lottie-ios', '4.6.0'
  pod 'PKHUD'
  pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :branch => 'master'
  pod 'Alamofire', '~> 5.11.2'
  pod 'SwiftKeychainWrapper'
  pod 'PanModal', :git => 'https://github.com/sharetripnet/PanModal.git'
  pod 'SkeletonView', '~> 1.30.4'
  pod 'libPhoneNumber-iOS-Swift', '~> 1.7.0'
  pod 'FirebaseAnalytics', '~> 12.14.0'
  pod 'FloatingPanel', '3.0.0'
  pod 'FirebaseRemoteConfig', '~> 12.14.0'
  pod 'AnyCodable-FlightSchool'
  pod 'ActiveLabel', '~> 1.1.0'
  pod 'FirebaseMessaging', '~> 12.14.0'
  pod 'SwiftyJSON', '~> 5.0.2'
  pod 'XLPagerTabStrip'
  pod 'JTAppleCalendar'
  pod 'SVGKit'
  pod 'IQKeyboardManagerSwift', '8.0.0'
  pod "JWT"
  pod 'Socket.IO-Client-Swift'
  pod 'FirebaseCore' , '~> 12.14.0'
  pod 'FirebaseCrashlytics', '~> 12.14.0'
  pod 'FirebaseAuth', '~> 12.14.0'
  pod 'ActiveLabel', '~> 1.1.0'
  pod 'CRRefresh'
  pod 'ASCollectionView-SwiftUI', :git => 'https://github.com/sharetripnet/ASCollectionView.git', :branch => 'master'
  pod 'MHLoadingButton'

  # ST SDKs
  pod 'FlightSDK', :path => '../'
  
end

use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES' # do not remove
    end
    
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
    
  end
end
