platform :ios, '13.0'

target 'STExample' do
  
  # With specific versions
  pod 'lottie-ios', '3.5.0'
  pod 'Kingfisher', '~> 7.6.2'
  
  # Always latest
  pod "JWT"
  pod 'PKHUD'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'FloatingPanel'
  pod 'JTAppleCalendar'
  pod 'SwiftKeychainWrapper'
  pod 'Socket.IO-Client-Swift'
  pod 'IQKeyboardManagerSwift'
  
  # Firebase SDKs
  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseAuth'
  pod 'FirebaseRemoteConfig'
  pod 'FirebaseMessaging'
  pod 'FirebaseDynamicLinks'
  
  # Newly Added Pods
  pod 'CRRefresh'
  pod 'ActiveLabel'
  pod 'SkeletonView'
  pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :branch => 'master'
  pod 'MHLoadingButton'
  pod 'XLPagerTabStrip'
  
  # ST Forks
  pod 'PanModal', :git => 'https://github.com/sharetripnet/PanModal.git'
  pod 'SwiftEntryKit', :git => 'https://github.com/sharetripnet/SwiftEntryKit.git', :tag => '2.0.8'
  
  # ST SDKs
  pod 'FlightSDK', :path => '../'
  
end

use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES' # do not remove
    end
    
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
    
  end
end
