disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
  - line_length
  - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
  - trailing_whitespace
  - large_tuple
  - cyclomatic_complexity
#  - type_body_length
#  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
#  - variable_name
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - ShareTrip
  - STFlightKit
  - STCoreKit
  
excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
  - Frameworks
  - Products
  - NotificationService
  - SDKExampleApp
  - STCoreKit/Libraries
  - ShareTrip/Inactive

file_length:
  - 1000
function_body_length:
  - 75
  - 160
type_body_length:
  - 400 # Warning
  - 600 # Error
